server:
  port: 8081
  servlet:
    context-path: /profile
spring:
  neo4j:
    uri: bolt://localhost:7687
    authentication:
      username: neo4j
      password: Boder&2363

app:
  services:
    file:
      url: http://localhost:8084/